language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev
  - sudo apt-get install -qq libdb++-dev
  - sudo apt-get install -qq libminiupnpc-dev
  - sudo apt-get install curl
  - sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
  - sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update
  - sudo apt-get install libdb4.8-dev libdb4.8++-dev
  - sudo apt-get install libminiupnpc-dev
  - sudo apt-get install libzmq3-dev
  - sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler 
  - sudo apt-get install libqt4-dev libprotobuf-dev protobuf-compiler
install: true
script:
  - qmake  
  - make  
  - cd src  
  - make -f makefile.unix  
